apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-app
  namespace: argocd     
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/madhukar6143/kubernetes-cloud-deploymenttt.git
    targetRevision: main
    path: k8s
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
